config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :libros
  resources :multa
  resources :prestamos
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/prestamo.rb
class Prestamo < ApplicationRecord
  belongs_to :Usuario
end

app/controllers/prestamos_controller.rb
class PrestamosController < ApplicationController
  before_action :set_prestamo, only: [:show, :edit, :update, :destroy]

  # GET /prestamos
  # GET /prestamos.json
  def index
    @prestamos = Prestamo.all
  end

  # GET /prestamos/1
  # GET /prestamos/1.json
  def show
  end

  # GET /prestamos/new
  def new
    @prestamo = Prestamo.new
  end

  # GET /prestamos/1/edit
  def edit
  end

  # POST /prestamos
  # POST /prestamos.json
  def create
    @prestamo = Prestamo.new(prestamo_params)

    respond_to do |format|
      if @prestamo.save
        format.html { redirect_to @prestamo, notice: 'Prestamo was successfully created.' }
        format.json { render :show, status: :created, location: @prestamo }
      else
        format.html { render :new }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prestamos/1
  # PATCH/PUT /prestamos/1.json
  def update
    respond_to do |format|
      if @prestamo.update(prestamo_params)
        format.html { redirect_to @prestamo, notice: 'Prestamo was successfully updated.' }
        format.json { render :show, status: :ok, location: @prestamo }
      else
        format.html { render :edit }
        format.json { render json: @prestamo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prestamos/1
  # DELETE /prestamos/1.json
  def destroy
    @prestamo.destroy
    respond_to do |format|
      format.html { redirect_to prestamos_url, notice: 'Prestamo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prestamo
      @prestamo = Prestamo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prestamo_params
      params.require(:prestamo).permit(:fecha, :estado, :Usuario_id)
    end
end

app/helpers/prestamos_helper.rb
module PrestamosHelper
end

app/views/prestamos/_form.html.erb
<%= form_with(model: prestamo, local: true) do |form| %>
  <% if prestamo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prestamo.errors.count, "error") %> prohibited this prestamo from being saved:</h2>

      <ul>
        <% prestamo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha %>
    <%= form.date_select :fecha %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.check_box :estado %>
  </div>

  <div class="field">
    <%= form.label :Usuario_id %>
    <%= form.select :Usuario_id, options_for_select(Usuario.all.map{|s|[s.nombres+" "+s.apellidos, s.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prestamos/edit.html.erb
<h1>Editing Prestamo</h1>

<%= render 'form', prestamo: @prestamo %>

<%= link_to 'Show', @prestamo %> |
<%= link_to 'Back', prestamos_path %>

app/views/prestamos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prestamos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Estado</th>
      <th>Usuario</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @prestamos.each do |prestamo| %>
      <tr>
        <td><%= prestamo.fecha %></td>
        <td><%= prestamo.estado %></td>
        <td><%= prestamo.Usuario.id.to_s+" - "+prestamo.Usuario.nombres+" "+prestamo.Usuario.apellidos %></td>
        <td><%= link_to 'Show', prestamo,:class => "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_prestamo_path(prestamo), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', prestamo, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prestamo', new_prestamo_path,:class => "btn btn-success" %>

app/views/prestamos/new.html.erb
<h1>New Prestamo</h1>

<%= render 'form', prestamo: @prestamo %>

<%= link_to 'Back', prestamos_path %>

app/views/prestamos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @prestamo.fecha %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @prestamo.estado %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @prestamo.Usuario.id.to_s+" - "+@prestamo.Usuario.nombres+" "+@prestamo.Usuario.apellidos %>
</p>

<%= link_to 'Edit', edit_prestamo_path(@prestamo) %> |
<%= link_to 'Back', prestamos_path %>