config/routes.rb
Rails.application.routes.draw do
  resources :detalles
  resources :libros
  resources :multa
  resources :prestamos
  resources :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor, :anyo)
    end
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
        <% libro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label "Año" %>
    <%= form.number_field :anyo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libros</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Autor</th>
      <th>Año</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.titulo %></td>
        <td><%= libro.autor %></td>
        <td><%= libro.anyo %></td>
        <td><%= link_to 'Show', libro,:class => "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro), :class => "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: {confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path,:class => "btn btn-success" %>

app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @libro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @libro.autor %>
</p>

<p>
  <strong>Año:</strong>
  <%= @libro.anyo %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>